### ISSUE TITLE
Can you please add a link to pull requester that open directly this form?

### ISSUE THREAD

**Issue by direction** [abelmartin/pull-requester#39]
This is kinda cheeky but SUPER useful

It could be like a feedback link or something

**Comment by abelmartin** [comment]
Hmm....

**Comment by abelmartin** [comment]
![screen shot 2013-09-19 at 2 10 33 am](https://f.cloud.github.com/assets/29429/1170868/416c9b82-20f2-11e3-9f16-97c94731ae56.png)
