### ISSUE TITLE
Issues/Features feels like it belongs to the repos you're watching

### ISSUE THREAD

**Issue by direction** [abelmartin/pull-requester#42]
Maybe a good spot would be the footer

**Comment by abelmartin** [comment]
You're a footer! :)

On Thu, Sep 19, 2013 at 9:57 AM, Disha Al Baqui notifications@github.comwrote:

> Maybe a good spot would be the footer
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/abelmartin/pull-requester/issues/42
> .

## 

@abelmartin https://twitter.com/abelmartin

**Comment by abelmartin** [comment]
![screen shot 2013-09-28 at 12 37 16 am](https://f.cloud.github.com/assets/29429/1230679/c2f4f4c2-27f7-11e3-9a19-bdc46c12474e.png)

**Comment by abelmartin** [comment]
I also updated the name in the menu from `Watch Settings` to `Repository Settings`.  I need to figure out better names for things :stuck_out_tongue_winking_eye:
