### ISSUE TITLE
Not seeing my personal private repositories

### ISSUE THREAD

**Issue by rmw** [abelmartin/pull-requester#43]
In the watch list, I'm not seeing any of my personal private repos ... but I see them for organizations (or at least HAW)

**Comment by abelmartin** [comment]
Yup, [this is a known issue](https://github.com/abelmartin/pull-requester/issues/23) but maybe I'll move it up to the v1.0 release

**Comment by abelmartin** [comment]
Moved up to v1.0 :smile:
