### ISSUE TITLE
Ability to assign a reviewer from the dashboard

### ISSUE THREAD

**Issue by direction** [abelmartin/pull-requester#47]
- Maybe V1 can be just for users in an organization and not available for public repos

**Comment by abelmartin** [comment]
Yeah, this is a good one.

As we discussed:
- I can start this as a feature for repos owned by an org
  - Might need to figure out a good way to get GH style autocomplete-searching going (hmm....).
- This feature can be seen as a democratic means for assigning PRs.

**Comment by abelmartin** [comment]
Completed In cdf3422d5c46464a764d62c073f9daad73af3933
