### ISSUE TITLE
Emoji Support

### ISSUE THREAD

**Issue by abelmartin** [abelmartin/pull-requester#5]

**Comment by raycchan** [comment]
:+1: :+1: :+1: :dancer: :dancers:

**Comment by abelmartin** [comment]
[Fixed in commit 8d85dacf2df8e68942ea0d4e7b78a198cd6513b5](https://github.com/abelmartin/pull-requester/commit/8d85dacf2df8e68942ea0d4e7b78a198cd6513b5)
