### ISSUE TITLE
Account Settings is throwing an error

### ISSUE THREAD

**Issue by direction** [abelmartin/pull-requester#75]
![screen shot 2014-05-09 at 10 43 07 am](https://cloud.githubusercontent.com/assets/10589/2929316/47655f04-d788-11e3-8bbd-6770e75d7b78.png)

**Comment by abelmartin** [comment]
Yup, I see what I did there. :sweat_smile:  Fix coming momentarily. :smile:

**Comment by direction** [comment]
yay - :smile: thanks

**Comment by abelmartin** [comment]
Deployed! :smile: 
![screen shot 2014-05-09 at 12 08 49 pm](https://cloud.githubusercontent.com/assets/29429/2930296/4c62b702-d794-11e3-8059-4d6da8c39d3c.png)
